"""Fixed models

Revision ID: 3f259fc9844d
Revises: 3aed872f7efa
Create Date: 2022-08-03 10:20:27.381886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f259fc9844d'
down_revision = '3aed872f7efa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['user_id'])
    op.add_column('users', sa.Column('user_email', sa.Text(), nullable=True))
    op.drop_constraint('users_task_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'task_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('users_task_id_fkey', 'users', 'tasks', ['task_id'], ['task_id'])
    op.drop_column('users', 'user_email')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'user_id')
    # ### end Alembic commands ###
